#!/usr/bin/env python3
"""
Voice profile: skeleton + helpers.

voice.md has two authoritative blocks, separated by two sentinels:

    # User voice
    <metadata>

    <!-- MINION_VOICE_AUTO_DRAFT -->
    <Claude-written block; produced via the `commit_voice` MCP tool>
    <!-- MINION_VOICE_USER_EDITS -->
    <hand-edited block; survives every regeneration>

Rationale
---------
Earlier iterations tried regex extraction from chat transcripts and produced
noise: "write the words Enter and Exit above the sliding doors" looks exactly
like a voice directive but is about a generated asset; "don't want a table on
the left" is about UI, not style. Only a capable LLM can reliably separate
voice directives from content directives.

So voice is built by Claude itself:

1. On first session where voice is unbuilt, `initialize.instructions` carries
   a bootstrap directive that tells Claude to gather evidence via its existing
   retrieval tools (`ask_minion` mode=relevance, role=user; `browse_conversations`)
   and then call `commit_voice` with synthesized markdown. This script writes
   only the skeleton; Claude fills the AUTO_DRAFT block.
2. Subsequent sessions: the committed voice is injected every time.
3. The user can hand-edit anything below USER_EDITS_SENTINEL; those edits
   survive rebuilds and re-bootstraps.

This module exposes:

- `build_skeleton(derived_dir)`: ensure voice.md exists with both sentinels.
- `is_voice_built(voice_md)`: True if either block has non-stub content.
- `sample_user_utterances(chunks_path, k, ...)`: legacy stratified sampler;
  unused by the current bootstrap path but kept for offline inspection.
- `write_auto_draft(voice_md_path, markdown)`: replace AUTO_DRAFT block.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple


AUTO_DRAFT_SENTINEL = "<!-- MINION_VOICE_AUTO_DRAFT -->"
USER_EDITS_SENTINEL = "<!-- MINION_VOICE_USER_EDITS -->"

AUTO_DRAFT_STUB = (
    "_(not yet built. Claude populates this block on the first MCP session "
    "via the bootstrap directive in `initialize.instructions` + `commit_voice`. "
    "One-time, silent. Persists forever.)_"
)

USER_EDITS_HEADER = (
    "## Your hand edits (preserved across rebuilds)\n"
    "\n"
    "_Edit freely below. Everything here survives `minion build-voice` and "
    "every future `commit_voice` call. Use this block to add durable rules the "
    "auto-draft missed, or to override it._\n"
)


# ---------------------------------------------------------------------------
# Skeleton read/write
# ---------------------------------------------------------------------------


def _split_blocks(text: str) -> Tuple[str, str, str]:
    """Return (header, auto_draft_body, user_edits_body).

    Unknown layouts fall back to: header = whole file, both bodies empty.
    """
    auto_i = text.find(AUTO_DRAFT_SENTINEL)
    user_i = text.find(USER_EDITS_SENTINEL)

    if auto_i < 0 and user_i < 0:
        return text, "", ""

    if auto_i < 0:
        # Old-format file with only USER_EDITS sentinel: treat whole pre-sentinel
        # as header, leave auto_draft empty, preserve post-sentinel as edits.
        return text[:user_i].rstrip() + "\n", "", text[user_i + len(USER_EDITS_SENTINEL):].lstrip("\n")

    if user_i < 0 or user_i < auto_i:
        # Only AUTO_DRAFT present (or malformed): everything after AUTO_DRAFT
        # becomes the draft body; no user edits.
        return (
            text[:auto_i].rstrip() + "\n",
            text[auto_i + len(AUTO_DRAFT_SENTINEL):].lstrip("\n"),
            "",
        )

    header = text[:auto_i].rstrip() + "\n"
    auto_body = text[auto_i + len(AUTO_DRAFT_SENTINEL):user_i].strip("\n")
    user_body = text[user_i + len(USER_EDITS_SENTINEL):].lstrip("\n")
    return header, auto_body, user_body


def _render(header: str, auto_body: str, user_body: str) -> str:
    auto_body = (auto_body or "").strip("\n") or AUTO_DRAFT_STUB
    user_body = (user_body or "").strip("\n") or USER_EDITS_HEADER
    return (
        f"{header.rstrip()}\n"
        f"\n"
        f"{AUTO_DRAFT_SENTINEL}\n"
        f"\n"
        f"{auto_body}\n"
        f"\n"
        f"{USER_EDITS_SENTINEL}\n"
        f"\n"
        f"{user_body}\n"
    )


def _default_header(n_chunks: int) -> str:
    today = datetime.utcnow().strftime("%Y-%m-%d")
    return (
        "# User voice\n"
        "\n"
        "_Injected into `initialize.instructions` every session as binding "
        "style and preference directives. Built once by Claude on first "
        "session via the bootstrap directive + `commit_voice`, then persisted._\n"
        "\n"
        f"_Skeleton generated by `minion build-voice` on {today}. "
        f"Source corpus: {n_chunks} chunks._\n"
    )


def build_skeleton(derived_dir: Path) -> Path:
    """Ensure voice.md exists with both sentinels. Preserves existing blocks."""
    chunks_path = derived_dir / "chunks.jsonl"
    n_chunks = 0
    if chunks_path.is_file():
        with chunks_path.open("r", encoding="utf-8") as f:
            for _ in f:
                n_chunks += 1

    out_path = derived_dir / "voice.md"
    if out_path.exists():
        existing = out_path.read_text(encoding="utf-8")
        header, auto_body, user_body = _split_blocks(existing)
        if not header.strip().startswith("# User voice"):
            header = _default_header(n_chunks)
    else:
        header = _default_header(n_chunks)
        auto_body = ""
        user_body = ""

    out_path.write_text(_render(header, auto_body, user_body), encoding="utf-8")
    return out_path


def is_voice_built(voice_md_text: str) -> bool:
    """True if either block has non-stub content."""
    _, auto_body, user_body = _split_blocks(voice_md_text)

    def _is_stub(body: str) -> bool:
        if not body.strip():
            return True
        if AUTO_DRAFT_STUB.strip() in body:
            return True
        # USER_EDITS_HEADER marker: if body is only the header stub, treat as empty.
        if body.strip() == USER_EDITS_HEADER.strip():
            return True
        return False

    return not (_is_stub(auto_body) and _is_stub(user_body))


def write_auto_draft(voice_md_path: Path, markdown: str, *, n_chunks: int = 0) -> None:
    """Replace the AUTO_DRAFT block. Preserves USER_EDITS block.

    Writes a fresh skeleton if the file doesn't exist yet.
    """
    if voice_md_path.exists():
        existing = voice_md_path.read_text(encoding="utf-8")
        header, _, user_body = _split_blocks(existing)
        if not header.strip().startswith("# User voice"):
            header = _default_header(n_chunks)
    else:
        header = _default_header(n_chunks)
        user_body = ""

    voice_md_path.write_text(_render(header, markdown, user_body), encoding="utf-8")


VOICE_SECTIONS: Tuple[str, ...] = (
    "Typography",
    "Formatting",
    "Length and density",
    "Tone and register",
    "Style references",
    "Hard nos",
    "Voice sample",
)

_INSUFFICIENT_MARKER = "_(insufficient signal)_"


def _normalize_line(s: str) -> str:
    """Collapse whitespace + lowercase for idempotency comparisons."""
    return re.sub(r"\s+", " ", s).strip().lower()


def append_to_section(auto_body: str, section: str, content: str) -> Tuple[str, bool]:
    """Append `content` under `### {section}` in the AUTO_DRAFT body.

    Returns (new_body, appended). `appended=False` means the content was already
    present (by normalized comparison) and nothing changed.

    Behavior:
    - If the section's body is empty or just `_(insufficient signal)_`, replace
      with `content`.
    - Otherwise append `content` as a new paragraph after existing content.
    - If the section heading does not exist yet, append it at the end of the body.
    - Idempotent: if any existing line normalizes to the same text, no-op.
    """
    if section not in VOICE_SECTIONS:
        raise ValueError(
            f"unknown section {section!r}. expected one of: {list(VOICE_SECTIONS)}"
        )
    content = content.strip()
    if not content:
        raise ValueError("content must not be empty")

    lines = auto_body.splitlines()
    heading = f"### {section}"

    # Locate the section block: from heading line through next H3 (or EOF).
    start_idx = None
    for i, line in enumerate(lines):
        if line.strip() == heading:
            start_idx = i
            break

    if start_idx is None:
        # Section missing — append heading + content at end.
        suffix = "" if auto_body.endswith("\n") or not auto_body else "\n"
        new_body = (
            auto_body.rstrip("\n")
            + ("\n\n" if auto_body.strip() else "")
            + f"{heading}\n{content}\n"
        )
        return new_body, True

    # Find end of section.
    end_idx = len(lines)
    for j in range(start_idx + 1, len(lines)):
        if lines[j].startswith("### "):
            end_idx = j
            break

    section_body = "\n".join(lines[start_idx + 1:end_idx]).strip("\n")
    normalized_existing = {
        _normalize_line(ln) for ln in section_body.splitlines() if ln.strip()
    }
    if _normalize_line(content) in normalized_existing:
        return auto_body, False
    # Also skip if the entire content normalizes into what's already there
    # (handles multi-line paragraphs appended previously).
    if _normalize_line(section_body) == _normalize_line(content):
        return auto_body, False

    # Treat a body that's only the insufficient-signal marker (with or without
    # a leading bullet) as empty for append purposes.
    body_stripped = section_body.strip()
    if body_stripped.startswith(("-", "*")):
        body_stripped = body_stripped.lstrip("-*").strip()
    is_stub = (not section_body) or body_stripped == _INSUFFICIENT_MARKER

    if is_stub:
        new_section_body = content
    else:
        new_section_body = section_body + "\n\n" + content

    new_lines = (
        lines[:start_idx + 1]
        + [""]
        + new_section_body.splitlines()
        + ([""] if end_idx < len(lines) else [])
        + lines[end_idx:]
    )
    return "\n".join(new_lines).strip("\n"), True


def append_to_voice_file(
    voice_md_path: Path, section: str, content: str, *, n_chunks: int = 0
) -> Tuple[bool, int]:
    """Append to AUTO_DRAFT section in voice.md. Returns (appended, new_size_bytes).

    Creates the skeleton if the file doesn't exist yet. Preserves header,
    USER_EDITS block, and all other AUTO_DRAFT sections.
    """
    if voice_md_path.exists():
        existing = voice_md_path.read_text(encoding="utf-8")
        header, auto_body, user_body = _split_blocks(existing)
        if not header.strip().startswith("# User voice"):
            header = _default_header(n_chunks)
    else:
        header = _default_header(n_chunks)
        auto_body = ""
        user_body = ""

    # Strip stub placeholder so we don't append beneath it.
    if auto_body.strip() == AUTO_DRAFT_STUB.strip():
        auto_body = ""

    new_body, appended = append_to_section(auto_body, section, content)
    out = _render(header, new_body, user_body)
    voice_md_path.write_text(out, encoding="utf-8")
    return appended, len(out.encode("utf-8"))


# ---------------------------------------------------------------------------
# Sampling (legacy; retained for offline inspection via `minion build-voice`)
# ---------------------------------------------------------------------------


_NOISE_RE = re.compile(
    r"```|[`{}<>|\[\]]{2,}|https?://|"
    r"</?\w+[^>]*>|style\s*=|class\s*=|color\s*:\s*#|font-"
)


def _is_noisy(text: str) -> bool:
    if _NOISE_RE.search(text):
        return True
    letters = sum(1 for c in text if c.isalpha())
    return letters < max(20, int(len(text) * 0.55))


def sample_user_utterances(
    chunks_path: Path,
    *,
    k: int = 40,
    min_chars: int = 80,
    max_chars: int = 600,
    seed: int = 0,
) -> List[Dict]:
    """Return a stratified sample of user utterances across conversations.

    Strategy:
      1. Keep user-role chunks with min_chars <= len <= max_chars, no heavy code/URL noise.
      2. One per conversation (favor medium-length chunks: information-dense).
      3. Sort candidates by create_time desc; keep most recent 3*k as pool.
      4. Return a random-but-seeded sample of size k from the pool.
    """
    if not chunks_path.is_file():
        return []

    best_per_conv: Dict[str, Dict] = {}
    with chunks_path.open("r", encoding="utf-8") as f:
        for line in f:
            try:
                ch = json.loads(line)
            except json.JSONDecodeError:
                continue
            if (ch.get("role") or "").lower() != "user":
                continue
            text = (ch.get("text") or "").strip()
            if not text or len(text) < min_chars or len(text) > max_chars:
                continue
            if _is_noisy(text):
                continue
            if "\n" in text:
                head = text.split("\n", 1)[0]
                if len(head) < min_chars:
                    continue
            conv_id = ch.get("conversation_id") or ch.get("id") or ""
            if not conv_id:
                continue
            # Preference function: closer to 250 chars is ideal (dense but not code).
            score = -abs(len(text) - 250)
            prior = best_per_conv.get(conv_id)
            if prior is None or score > prior["__score"]:
                ch = dict(ch)
                ch["__score"] = score
                best_per_conv[conv_id] = ch

    pool = list(best_per_conv.values())
    pool.sort(key=lambda c: c.get("create_time") or 0, reverse=True)
    pool = pool[: max(k * 3, 60)]

    rng = random.Random(seed)
    rng.shuffle(pool)
    chosen = pool[:k]

    out: List[Dict] = []
    for ch in chosen:
        out.append({
            "conversation_id": ch.get("conversation_id") or ch.get("id") or "",
            "create_time": ch.get("create_time"),
            "text": ch.get("text") or "",
            "char_count": len(ch.get("text") or ""),
        })
    return out


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Ensure voice.md skeleton exists")
    ap.add_argument("--derived-dir", required=True, help="Directory containing chunks.jsonl")
    args = ap.parse_args(argv)

    derived = Path(args.derived_dir).expanduser().resolve()
    path = build_skeleton(derived)
    built = is_voice_built(path.read_text(encoding="utf-8"))
    status = "populated" if built else "stub (Claude will bootstrap on first session)"
    print(f"Wrote {path} ({path.stat().st_size} bytes). Status: {status}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
